### ISSUE TITLE
快捷键无响应

### ISSUE THREAD

**Issue by anyunshen** [Howardzhangdqs/web-select#1]
快捷键无响应

**Comment by Howardzhangdqs** [comment]
按的是 `Alt+S` 吗，和微软官网的快捷键不太一样。如果 `Alt+S` 没反应的话能不能提供一下浏览器版本、以及页面等信息，谢谢

**Comment by anyunshen** [comment]
是按的alt+s，浏览器是edge 版本 120.0.2210.61 (正式版本) stable应用，beta频道 (64 位)

**Comment by Howardzhangdqs** [comment]
是所有页面都没反应吗

**Comment by anyunshen** [comment]
是的

**Comment by Howardzhangdqs** [comment]
Edge Beta我没复现成功，你是在Greasyfork里安装的吗

**Comment by Howardzhangdqs** [comment]
我真的没复现出来类似的问题
我怀疑可能是监听器在部分网页上没能成功挂载，我再试试
